FROM golang:1.17 as builder
ADD . /app
WORKDIR /app
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o spelling .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder app/spelling .
COPY --from=builder app/dic .
EXPOSE 80
CMD ["./spelling"]