FROM golang:1.17 as builder
ADD . /app
WORKDIR /app
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o ./bin/ ./examples/service.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder app/bin/service .
COPY --from=builder app/dictionaries .
EXPOSE 80
CMD ["./spelling ./dictionaries/es.dic"]